### ISSUE TITLE
Timestamps problems?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#183] opened 2024-01-11 21:36 UTC
Eli Sennesh from GLO said
```
In the following files:
sub-1199273437_ses-1214578117.nwb  sub-1210326253_ses-1221092548.nwb  sub-1214404694_ses-1224930300.nwb  sub-1214890319_ses-1226526314.nwb  sub-1218586779_ses-1227858756.nwb  sub-1223032979_ses-1232959154.nwb
the sampling timestamps for LFPs and the event timestamps used for tracking the start/end of trials and the onset/offset of stimuli don't seem to use the same zero-point or scale.  For instance, in some files there are negative timestamps leading up to a few seconds' worth of positive timestamps in the timestamps array, and then entirely positive timestamps (going up to the hundreds of seconds) for events.
```

**Comment by rcpeene** [comment] 2024-01-12 18:52
I checked the stim file and probe file for `sub_1199273437sess_1214578117/sub_1199273437+sess_1214578117`
Here are the stim timestamps and LFP timestamps



![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/29e9b3f8-ba60-4f56-8855-ff84343f5659)



![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/11a59d93-c00f-44fd-82c6-93283e9a68b5)

And this indeed looks off. The LFP timestamps start at 5000, long after the stim timestamps begin

**Comment by rcpeene** [comment] 2024-01-13 00:58
For `sub_1210326253/sub_1210326253sess_1221092548/sub_1210326253+sess_1221092548_ecephys.nwb`,  I received these timestamp results
```
First timestamp stimulus data:  75.29793470943362
Last timestamp stimulus data:  6837.985915177345
First timestamp LFP data:  3.5540781836822246
Last timestamp LFP data:  3.5667492072474234
```



![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/68ac6da6-80fd-4dfb-9757-babd05fcf8fe)


![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/23059582/130fc649-649b-40eb-9c2b-772129d20bee)

**Comment by jeromelecoq** [comment] 2024-01-16 19:09
We need to look at AllenSDK code for How downsampling is managed.

**Comment by Ahad-Allen** [comment] 2024-01-29 17:24
We figured out that this was being caused by the switch to a newer open ephys pipeline for later GLO sessions, it has been resolved by using the same packaging trick of looking at the sample numbers.npy that we use for vippo and barcoding.

**Comment by jeromelecoq** [comment] 2024-07-30 18:28
@rcpeene to confirm that alignment still has issues.

**Comment by rcpeene** [comment] 2024-08-20 18:09
@Ahad-Allen close if confirmed

**Closed as completed** 2024-09-03 14:42 UTC
