### ISSUE TITLE
If a probe is missing, CCF alignment does not work

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#89] opened 2023-01-17 19:17 UTC

**Comment by jeromelecoq** [comment] 2023-01-17 19:18
We need to find session where one or more probe is missing and re-run CCF alignment + NWB conversion.

**Comment by jeromelecoq** [comment] 2023-01-17 19:18
@Ahad-Allen to give severing the list of session with issues.

**Comment by Ahad-Allen** [comment] 2023-01-17 23:26
I sent Severine hannah and Ben a list of the sessions. It seems only 3 sessions were affected, and she is already running the redos. probes are 1179909741, 1194857009, and possibly 1196362744 (this one is marked as having a problem with b, but I was not sure if it was failed).

**Comment by Ahad-Allen** [comment] 2023-01-19 18:07
Sev has redone the alignment and ben has triggered the uploads.

**Comment by Ahad-Allen** [comment] 2023-01-19 22:49
We are waiting on this as There are some probe areas that need to be redone because of the bug that Sev discovered. She will update me on progress for them all tomorrow :)

**Comment by Ahad-Allen** [comment] 2023-01-24 18:11
I met with Sev and Hannah yesterday about this and they shared a document showing all the sessions that need to be reuploaded and with corrected locations. I will work on the regeneration and upload of these today and then close the issue when they are up on dandi. There are some issues with some sessions having probe depth issues. These are corrected but awaiting an upload from zeb. I can get these onto dandi once that upload is done.

**Comment by Ahad-Allen** [comment] 2023-01-25 18:51
All but one of the illusion session shave been regenerated, and some of the GLO as well. I am fixing an issue where the blank folders caused by Ben's deletion are causing a conversion issue, but after that string input for my glob is completed we should be fine to convert those.

**Comment by jeromelecoq** [comment] 2023-01-25 19:06
We will chat with sev

**Comment by Ahad-Allen** [comment] 2023-01-26 17:08
Sev was able to work with Ben to get the probe info json files updated. I will convert them now!

**Comment by Ahad-Allen** [comment] 2023-01-27 18:48
Every session except for 1233182025 is converted! The d1 upload for this was not fully triggered, but ben has resolved this and says all the files should be up for it around 2pm. Once those are done, we can convert and we will have every single session for both projects!

**Closed** 2023-01-31 02:20 UTC
