### ISSUE TITLE
Fix our Dandisets Metadata?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#91] opened 2023-01-20 23:03 UTC
In [this issue](https://github.com/dandi/dandi-cli/issues/1189) we discovered that our dandisets may have invalid metadata. We should  run the files through the nwb viewer and try the suggestion that issue.

**Comment by satra** [comment] 2023-01-23 22:19
@rcpeene - how are you creating the metadata? if programmatically, i would suggest using the dandischema library itself to check validation before upload.

**Comment by jeromelecoq** [comment] 2023-02-03 19:22
The cmd is asset.get_metadata should function

**Comment by satra** [comment] 2023-02-03 20:19
@jeromelecoq - i shared [this function](https://github.com/catalystneuro/neuroconv/blob/a0f89d2e7370f3aa8ef4309d717faf9bcc76f146/src/neuroconv/tools/data_transfers.py#L290-L297) that @CodyCBakerPhD wrote with @Ahad-Allen

**Comment by Ahad-Allen** [comment] 2023-02-08 18:44
This should be fixed by #94 once the issue with order_of_images is resolved.

**Comment by jeromelecoq** [comment] 2023-02-15 19:09
Carter needs to download one file and check it

**Comment by jeromelecoq** [comment] 2023-02-17 18:50
This is a problem for both ephys and ophys? 
Ahad is working on ophys right now. 
The fix seems to work on them. 
We need to apply to all ephys as well.

**Comment by rcpeene** [comment] 2023-02-17 20:10
Yeah ophys metadata works now, but ecephys doesn't.

**Comment by Ahad-Allen** [comment] 2023-02-21 18:31
We will need to create a script for ecephys uploads.

**Comment by jeromelecoq** [comment] 2023-03-17 18:14
@ahad will send a link to Ahad to check ecephys file work for one with metadata extraction. 
@Carter to add code/stack to reproduce error.

**Comment by rcpeene** [comment] 2023-03-17 18:15
Error shown here from my failed notebook; https://github.com/AllenInstitute/openscope_databook/actions/runs/4420172853/jobs/7749536642

**Comment by jeromelecoq** [comment] 2023-03-21 21:20
All ephys files needs to be reuploaded to fix this.

**Comment by jeromelecoq** [comment] 2023-03-22 18:13
@Ahad-Allen Can you link the script to fix to this issue?

**Comment by Ahad-Allen** [comment] 2023-03-23 17:27
The script is running and working! you can see it here :) https://github.com/AllenInstitute/OpenScopeNWB/pull/106/commits/a6bc9f12274c382418085939e1b4de401fa7b61f

**Comment by Ahad-Allen** [comment] 2023-03-27 17:55
I need to go session by session to confirm everything looks good, but all the LFP files appear to have been generated correctly!

**Comment by Ahad-Allen** [comment] 2023-03-29 17:52
I have identified the problem. The problem seems to be that the NWB file name was coming from the id information from the subject field. That info was being pulled from lims with the following query: [http://lims2/donors/info/details.json?external_donor_name=](http://lims2/donors/info/details.json?external_donor_name=631188){} where {} contains the donor id for the session. The problem seems to be that the id returned there is a 10 digit id, but is not the 10 digit specimen id that is present in the allen institute file paths and such. For example: For experiment 1210474579 the donor id is 631188. The 10 digit id returned by the donor url ([http://lims2/donors/info/details.json?external_donor_name=631188](http://lims2/donors/info/details.json?external_donor_name=)) is 1186140941. That is distinct from the specimen id we expect, which is 1186140952. 

The safest way to fix this is just querying the filepath and grabbing the specimen number from the allen directory.

**Comment by jeromelecoq** [comment] 2023-03-29 18:19
We agreed to :
1/ Use the external specimen id (6 digits currently) for all fields and path associated with mice. 
2/ In the NWB description field associated with the subject, we will add a test like so: 
specimen_id : XXXXXXX, donor_id : XXXXXXX, external_specimen_id: XXXXXX

**Comment by jeromelecoq** [comment] 2023-03-29 18:20
This means regenerating all NWB files and paths for all projects.

**Comment by jeromelecoq** [comment] 2023-03-30 19:05
@Ahad-Allen  we can start with ephys

**Closed** 2023-04-13 16:24 UTC
Labels: bug
