### ISSUE TITLE
Units table not loaded correctly in ecephys NWB files

### ISSUE THREAD

**Issue by jsiegle** [AllenInstitute/OpenScopeNWB#24] opened 2021-10-29 18:09 UTC
The ecephys NWB files generated by the current version of `OpenScopeNWB` do not load correctly. Specifically, querying the `units` property of the `EcephysSession` object returns an empty DataFrame. The correct behavior would be to return a DataFrame with a row for every unit in the dataset.

**Comment by Ahad-Allen** [comment] 2021-11-05 21:02
This issue was being caused by an id mismatch between the channel and unit dictionaries with regards to the peak_channel information. This should have been resolved with the latest code update, as the id now follows the formula Josh used in his version of the SDK. I am not marking it as resolved quite yet, though, as I would like to generate the previously generated NWBs and verify that all of them display their unit tables correctly.

**Closed** 2021-11-24 17:15 UTC
