### ISSUE TITLE
Look into low-bitdepth projection images in NWB files?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#108] opened 2023-03-17 19:36 UTC
Today when discussing how to use our NWB projection images for nway matching in [this](https://github.com/AllenInstitute/openscope_databook/issues/172) issue, we discovered that although the projection images are stored as 32 bit floating point values in the nwb.grayscaleimage type, our images have a very low bit-depth (like 5 or 6 values). Something is happening in our pipeline to reduce the image quality. @Ahad-Allen to investigate

**Comment by rcpeene** [comment] 2023-03-17 19:40
Here is the histogram of the color values in one of our images from dendritic coupling.


![Image](https://user-images.githubusercontent.com/23059582/226008733-0d3560be-d1d3-4a8b-8225-ab6f8f6d14ed.PNG)

**Comment by Ahad-Allen** [comment] 2023-03-17 20:13
The images seem to be coming from the 'processed' folder associated with each experiment. These images are continuous, so I am looking into how the image itself is inserted into the nwb. Here is the histogram of the image from the processing folder. 


![Image](https://user-images.githubusercontent.com/87045911/226025651-d99ce917-bb2f-4fe3-a85a-2b7ca7fa1905.png)

**Comment by Ahad-Allen** [comment] 2023-03-23 17:26
![Image](https://user-images.githubusercontent.com/87045911/227287554-8c5d01da-6adb-46f0-b52c-2f290c60d7e5.png)

got a response from adam on this! It seems like we can resolve this by updating our versioning :)

**Comment by rcpeene** [comment] 2023-03-23 18:02
Hmm okay, did you take a look at the code? I think even normalizing it 0,1 vs 0,255 wouldn't the complete explanation for the low bit-depth.

**Comment by Ahad-Allen** [comment] 2023-03-24 17:57
Ok, i think I've got this figured out. The query to grab the images has changed between allensdk versions! The new query is 

![Image](https://user-images.githubusercontent.com/87045911/227603352-bc2ff350-03ca-47f8-8f34-f5c56acf15fb.png)

while our old query is:


![Image](https://user-images.githubusercontent.com/87045911/227603398-50e3a140-6ed2-48c8-a84b-527f94cdf257.png)

We are grabbing files which are generated by the cell segementation pipeline, rather than the motion correction images. This explains why the motion correction images in the output folder of the sessions are continuous but the images within our sessions are discrete.

**Comment by Ahad-Allen** [comment] 2023-03-27 17:54
I have implemented a fix for this into our code and am generating an nwb for carter to review.

**Comment by jeromelecoq** [comment] 2023-03-27 18:35
@Ahad-Allen will generate the files that Carter is using as a priority to unstuck cell matching work.

**Comment by jeromelecoq** [comment] 2023-03-28 18:15
Updating the query fixed the discontinuous distribution. Images are still stored as floating point and not 8 bit integers in the NWB. 
@Ahad-Allen will investigate to check whether the raw images are being upcasted to float while being saved in the NWB files.

**Comment by jeromelecoq** [comment] 2023-03-30 19:12
We think the issue is matplotlib imread that is converting png to float. 
We agreed to bypass this call and use PIL.image instead. We will include that change in our branch of the allensdk and file an issue to the original repo.

**Comment by Ahad-Allen** [comment] 2023-03-31 16:57
I fixed the issue internally by using PIL image and created an issue for the sdk at: https://github.com/AllenInstitute/AllenSDK/issues/2672

**Closed** 2023-04-13 16:23 UTC
